export const ABILITIES = [
  { id: 'Adamant', name: 'Adamant' },
  { id: 'Addendum', name: 'Addendum' },
  { id: 'Alliance', name: 'Alliance' },
  { id: 'Battalion', name: 'Battalion' },
  { id: 'Best_in_show', name: 'Best in show' },
  { id: 'Bloodrush', name: 'Bloodrush' },
  { id: 'Channel', name: 'Channel' },
  { id: 'Chroma', name: 'Chroma' },
  { id: 'Cohort', name: 'Cohort' },
  { id: 'Constellation', name: 'Constellation' },
  { id: 'Converge', name: 'Converge' },
  { id: 'Council%27s_dilemma', name: 'Council\'s dilemma' },
  { id: 'Coven', name: 'Coven' },
  { id: 'Crash_Land', name: 'Crash Land' },
  { id: 'Delirium', name: 'Delirium' },
  { id: 'Domain', name: 'Domain' },
  { id: 'Eminence', name: 'Eminence' },
  { id: 'Enrage', name: 'Enrage' },
  { id: 'Family_gathering', name: 'Family gathering' },
  { id: 'Fateful_hour', name: 'Fateful hour' },
  { id: 'Ferocious', name: 'Ferocious' },
  { id: 'Flavor_word', name: 'Flavor word' },
  { id: 'Formidable', name: 'Formidable' },
  { id: 'Gear_up', name: 'Gear up' },
  { id: 'Gotcha', name: 'Gotcha' },
  { id: 'Grandeur', name: 'Grandeur' },
  { id: 'Hellbent', name: 'Hellbent' },
  { id: 'Hero%27s_Reward', name: 'Hero\'s Reward' },
  { id: 'Heroic', name: 'Heroic' },
  { id: 'Imprint', name: 'Imprint' },
  { id: 'Inspired', name: 'Inspired' },
  { id: 'Join_forces', name: 'Join forces' },
  { id: 'Kinfall', name: 'Kinfall' },
  { id: 'Kinship', name: 'Kinship' },
  { id: 'Landfall', name: 'Landfall' },
  { id: 'Landship', name: 'Landship' },
  { id: 'Lieutenant', name: 'Lieutenant' },
  { id: 'Magecraft', name: 'Magecraft' },
  { id: 'Metalcraft', name: 'Metalcraft' },
  { id: 'Morbid', name: 'Morbid' },
  { id: 'Pack_tactics', name: 'Pack tactics' },
  { id: 'Parade!', name: 'Parade!' },
  { id: 'Parley', name: 'Parley' },
  { id: 'Radiance', name: 'Radiance' },
  { id: 'Raid', name: 'Raid' },
  { id: 'Rally', name: 'Rally' },
  { id: 'Revolt', name: 'Revolt' },
  { id: 'Spell_mastery', name: 'Spell mastery' },
  { id: 'Strive', name: 'Strive' },
  { id: 'Sweep', name: 'Sweep' },
  { id: 'Tempting_offer', name: 'Tempting offer' },
  { id: 'Threshold', name: 'Threshold' },
  { id: 'Underdog', name: 'Underdog' },
  { id: 'Undergrowth', name: 'Undergrowth' },
  { id: 'Will_of_the_council', name: 'Will of the council' },
];
