export const KEYWORDS_ACTIONS = [
  { id: 'Abandon', name: 'Abandon' },
  { id: 'Activate', name: 'Activate' },
  { id: 'Adapt', name: 'Adapt' },
  { id: 'Amass', name: 'Amass' },
  { id: 'Ante', name: 'Ante' },
  { id: 'Assemble', name: 'Assemble' },
  { id: 'Attach', name: 'Attach' },
  { id: 'Ban', name: 'Ban' },
  { id: 'Bolster', name: 'Bolster' },
  { id: 'Bury', name: 'Bury' },
  { id: 'Cast', name: 'Cast' },
  { id: 'Challenge', name: 'Challenge' },
  { id: 'Circle', name: 'Circle' },
  { id: 'Clash', name: 'Clash' },
  { id: 'Combine', name: 'Combine' },
  { id: 'Conjure', name: 'Conjure' },
  { id: 'Connive', name: 'Connive' },
  { id: 'Convert', name: 'Convert' },
  { id: 'Counter', name: 'Counter' },
  { id: 'Crank', name: 'Crank' },
  { id: 'Create', name: 'Create' },
  { id: 'Destroy', name: 'Destroy' },
  { id: 'Detain', name: 'Detain' },
  { id: 'Discard', name: 'Discard' },
  { id: 'Double', name: 'Double' },
  { id: 'Double-tap', name: 'Double-tap' },
  { id: 'Draft_(keyword_action)', name: 'Draft (keyword action)' },
  { id: 'Exchange', name: 'Exchange' },
  { id: 'Exert', name: 'Exert' },
  { id: 'Exile', name: 'Exile' },
  { id: 'Explore', name: 'Explore' },
  { id: 'Fateseal', name: 'Fateseal' },
  { id: 'Fight', name: 'Fight' },
  { id: 'Goad', name: 'Goad' },
  { id: 'Hide', name: 'Hide' },
  { id: 'Install/Uninstall', name: 'Install/Uninstall' },
  { id: 'Investigate', name: 'Investigate' },
  { id: 'Jump_in_a_log', name: 'Jump in a log' },
  { id: 'Learn', name: 'Learn' },
  { id: 'Manifest', name: 'Manifest' },
  { id: 'Meld', name: 'Meld' },
  { id: 'Mill', name: 'Mill' },
  { id: 'Monstrosity', name: 'Monstrosity' },
  { id: 'Open_an_attraction', name: 'Open an attraction' },
  { id: 'Planeswalk', name: 'Planeswalk' },
  { id: 'Play', name: 'Play' },
  { id: 'Populate', name: 'Populate' },
  { id: 'Proliferate', name: 'Proliferate' },
  { id: 'Reflect', name: 'Reflect' },
  { id: 'Regenerate', name: 'Regenerate' },
  { id: 'Reveal', name: 'Reveal' },
  { id: 'Sacrifice', name: 'Sacrifice' },
  { id: 'Scry', name: 'Scry' },
  { id: 'Search', name: 'Search' },
  { id: 'Seek', name: 'Seek' },
  { id: 'Set_in_motion', name: 'Set in motion' },
  { id: 'Shuffle', name: 'Shuffle' },
  { id: 'Spark_(keyword_action)', name: 'Spark (keyword action)' },
  { id: 'Support', name: 'Support' },
  { id: 'Surveil', name: 'Surveil' },
  { id: 'Switch', name: 'Switch' },
  { id: 'Tap', name: 'Tap' },
  { id: 'Transform', name: 'Transform' },
  { id: 'Untap', name: 'Untap' },
  { id: 'Upgrade', name: 'Upgrade' },
  { id: 'Venture_into_the_dungeon', name: 'Venture into the dungeon' },
  { id: 'Visit', name: 'Visit' },
  { id: 'Vote', name: 'Vote' },
  { id: 'Wrap', name: 'Wrap' },
];

export const KEYWORDS_ACTIVATED = [
  { id: 'Augment', name: 'Augment' },
  { id: 'Aura_swap', name: 'Aura swap' },
  { id: 'Boast', name: 'Boast' },
  { id: 'Crew', name: 'Crew' },
  { id: 'Cycling', name: 'Cycling' },
  { id: 'Embalm', name: 'Embalm' },
  { id: 'Encore', name: 'Encore' },
  { id: 'Equip', name: 'Equip' },
  { id: 'Eternalize', name: 'Eternalize' },
  { id: 'Forecast', name: 'Forecast' },
  { id: 'Fortify', name: 'Fortify' },
  { id: 'Four-faced', name: 'Four-faced' },
  { id: 'Hieroglyphics', name: 'Hieroglyphics' },
  { id: 'Level_up', name: 'Level up' },
  { id: 'Mummify', name: 'Mummify' },
  { id: 'Ninjutsu', name: 'Ninjutsu' },
  { id: 'Outlast', name: 'Outlast' },
  { id: 'Reckless', name: 'Reckless' },
  { id: 'Reconfigure', name: 'Reconfigure' },
  { id: 'Reinforce', name: 'Reinforce' },
  { id: 'Scavenge', name: 'Scavenge' },
  { id: 'Specialize', name: 'Specialize' },
  { id: 'Transfigure', name: 'Transfigure' },
  { id: 'Transmute', name: 'Transmute' },
  { id: 'Unearth', name: 'Unearth' },
];

export const KEYWORDS_CHARACTERISTIC = [
  { id: 'Changeling', name: 'Changeling' },
  { id: 'Devoid', name: 'Devoid' },
  { id: 'Living_Metal', name: 'Living Metal' },
  { id: 'Rangeling', name: 'Rangeling' },
];

export const KEYWORDS_EVASION = [
  { id: 'Art_menace', name: 'Art menace' },
  { id: 'Blurry', name: 'Blurry' },
  { id: 'Denimwalk', name: 'Denimwalk' },
  { id: 'Fear', name: 'Fear' },
  { id: 'Flying', name: 'Flying' },
  { id: 'Horsemanship', name: 'Horsemanship' },
  { id: 'Intimidate', name: 'Intimidate' },
  { id: 'Landwalk', name: 'Landwalk' },
  { id: 'Menace', name: 'Menace' },
  { id: 'Shadow', name: 'Shadow' },
  { id: 'Skulk', name: 'Skulk' },
];

export const KEYWORDS_SPELL = [
  { id: 'Ascend', name: 'Ascend' },
  { id: 'Awaken', name: 'Awaken' },
  { id: 'Cipher', name: 'Cipher' },
  { id: 'Epic', name: 'Epic' },
];

export const KEYWORDS_STATIC = [
  { id: 'Absorb', name: 'Absorb' },
  { id: 'Affinity', name: 'Affinity' },
  { id: 'Aftermath', name: 'Aftermath' },
  { id: 'Aggressive', name: 'Aggressive' },
  { id: 'Alpha_strike', name: 'Alpha strike' },
  { id: 'Amplify', name: 'Amplify' },
  { id: 'Ascend', name: 'Ascend' },
  { id: 'Assist', name: 'Assist' },
  { id: 'Awaken', name: 'Awaken' },
  { id: 'Backbone', name: 'Backbone' },
  { id: 'Banding', name: 'Banding' },
  { id: 'Bank', name: 'Bank' },
  { id: 'Bestow', name: 'Bestow' },
  { id: 'Blitz', name: 'Blitz' },
  { id: 'Bloodthirst', name: 'Bloodthirst' },
  { id: 'Buyback', name: 'Buyback' },
  { id: 'Casualty', name: 'Casualty' },
  { id: 'Choose_a_Background', name: 'Choose a Background' },
  { id: 'Cipher', name: 'Cipher' },
  { id: 'Cleave', name: 'Cleave' },
  { id: 'Companion', name: 'Companion' },
  { id: 'Compleated', name: 'Compleated' },
  { id: 'Conspire', name: 'Conspire' },
  { id: 'Convoke', name: 'Convoke' },
  { id: 'Dash', name: 'Dash' },
  { id: 'Daybound_and_Nightbound', name: 'Daybound and Nightbound' },
  { id: 'Deathtouch', name: 'Deathtouch' },
  { id: 'Decayed', name: 'Decayed' },
  { id: 'Defender', name: 'Defender' },
  { id: 'Delve', name: 'Delve' },
  { id: 'Devour', name: 'Devour' },
  { id: 'Disturb', name: 'Disturb' },
  { id: 'Double_strike', name: 'Double strike' },
  { id: 'Dredge', name: 'Dredge' },
  { id: 'Emerge', name: 'Emerge' },
  { id: 'Enchant', name: 'Enchant' },
  { id: 'Enlist', name: 'Enlist' },
  { id: 'Entwine', name: 'Entwine' },
  { id: 'Escalate', name: 'Escalate' },
  { id: 'Escape', name: 'Escape' },
  { id: 'Evoke', name: 'Evoke' },
  { id: 'Fading', name: 'Fading' },
  { id: 'First_strike', name: 'First strike' },
  { id: 'Flash', name: 'Flash' },
  { id: 'Flashback', name: 'Flashback' },
  { id: 'Forbidden', name: 'Forbidden' },
  { id: 'Foretell', name: 'Foretell' },
  { id: 'Friends_forever', name: 'Friends forever' },
  { id: 'Fuse', name: 'Fuse' },
  { id: 'Gobble', name: 'Gobble' },
  { id: 'Graft', name: 'Graft' },
  { id: 'Haste', name: 'Haste' },
  { id: 'Hexproof', name: 'Hexproof' },
  { id: 'Hidden_agenda', name: 'Hidden agenda' },
  { id: 'Improvise', name: 'Improvise' },
  { id: 'Indestructible', name: 'Indestructible' },
  { id: 'Infect', name: 'Infect' },
  { id: 'Interplanar', name: 'Interplanar' },
  { id: 'Jump-start', name: 'Jump-start' },
  { id: 'Just_a_second', name: 'Just a second' },
  { id: 'Kicker', name: 'Kicker' },
  { id: 'Landhome', name: 'Landhome' },
  { id: 'Last_strike', name: 'Last strike' },
  { id: 'Legacy_(keyword)', name: 'Legacy (keyword)' },
  { id: 'Lifelink', name: 'Lifelink' },
  { id: 'Link', name: 'Link' },
  { id: 'Madness', name: 'Madness' },
  { id: 'Miracle', name: 'Miracle' },
  { id: 'Modular', name: 'Modular' },
  { id: 'More_Than_Meets_the_Eye', name: 'More Than Meets the Eye' },
  { id: 'Morph', name: 'Morph' },
  { id: 'Motivate', name: 'Motivate' },
  { id: 'Mutate', name: 'Mutate' },
  { id: 'Nostalgia', name: 'Nostalgia' },
  { id: 'Offering', name: 'Offering' },
  { id: 'Overload', name: 'Overload' },
  { id: 'Partner', name: 'Partner' },
  { id: 'Phasing', name: 'Phasing' },
  { id: 'Protection', name: 'Protection' },
  { id: 'Prototype', name: 'Prototype' },
  { id: 'Prowl', name: 'Prowl' },
  { id: 'Ravenous', name: 'Ravenous' },
  { id: 'Reach', name: 'Reach' },
  { id: 'Read_ahead', name: 'Read ahead' },
  { id: 'Rebound', name: 'Rebound' },
  { id: 'Replicate', name: 'Replicate' },
  { id: 'Retrace', name: 'Retrace' },
  { id: 'Riot', name: 'Riot' },
  { id: 'Scrycast', name: 'Scrycast' },
  { id: 'Shroud', name: 'Shroud' },
  { id: 'Space_sculptor', name: 'Space sculptor' },
  { id: 'Spectacle', name: 'Spectacle' },
  { id: 'Splice', name: 'Splice' },
  { id: 'Split_second', name: 'Split second' },
  { id: 'Squad', name: 'Squad' },
  { id: 'Substance', name: 'Substance' },
  { id: 'Sunburst', name: 'Sunburst' },
  { id: 'Super_haste', name: 'Super haste' },
  { id: 'Surge', name: 'Surge' },
  { id: 'Suspend', name: 'Suspend' },
  { id: 'Tasty', name: 'Tasty' },
  { id: 'Totem_armor', name: 'Totem armor' },
  { id: 'Trample', name: 'Trample' },
  { id: 'Tribute', name: 'Tribute' },
  { id: 'Triple_strike', name: 'Triple strike' },
  { id: 'Typelink', name: 'Typelink' },
  { id: 'Undaunted', name: 'Undaunted' },
  { id: 'Undeathtouch', name: 'Undeathtouch' },
  { id: 'Unique', name: 'Unique' },
  { id: 'Unleash', name: 'Unleash' },
  { id: 'Unstoppable', name: 'Unstoppable' },
  { id: 'Vanishing', name: 'Vanishing' },
  { id: 'Vigilance', name: 'Vigilance' },
  { id: 'Wither', name: 'Wither' },
];

export const KEYWORDS_TRIGGERED = [
  { id: 'Afflict', name: 'Afflict' },
  { id: 'Afterlife', name: 'Afterlife' },
  { id: 'Annihilator', name: 'Annihilator' },
  { id: 'Battle_cry', name: 'Battle cry' },
  { id: 'Bushido', name: 'Bushido' },
  { id: 'Cascade', name: 'Cascade' },
  { id: 'Casualty', name: 'Casualty' },
  { id: 'Champion', name: 'Champion' },
  { id: 'Conspire', name: 'Conspire' },
  { id: 'Cumulative_upkeep', name: 'Cumulative upkeep' },
  { id: 'Demonstrate', name: 'Demonstrate' },
  { id: 'Dethrone', name: 'Dethrone' },
  { id: 'Double_team', name: 'Double team' },
  { id: 'Echo', name: 'Echo' },
  { id: 'Evoke', name: 'Evoke' },
  { id: 'Evolve', name: 'Evolve' },
  { id: 'Exalted', name: 'Exalted' },
  { id: 'Exploit', name: 'Exploit' },
  { id: 'Extort', name: 'Extort' },
  { id: 'Fabricate', name: 'Fabricate' },
  { id: 'Fading', name: 'Fading' },
  { id: 'Flanking', name: 'Flanking' },
  { id: 'Frenzy', name: 'Frenzy' },
  { id: 'Glorify', name: 'Glorify' },
  { id: 'Graft', name: 'Graft' },
  { id: 'Gravestorm', name: 'Gravestorm' },
  { id: 'Haunt', name: 'Haunt' },
  { id: 'Hideaway', name: 'Hideaway' },
  { id: 'Ingest', name: 'Ingest' },
  { id: 'Living_weapon', name: 'Living weapon' },
  { id: 'Madness', name: 'Madness' },
  { id: 'Melee', name: 'Melee' },
  { id: 'Mentor', name: 'Mentor' },
  { id: 'Miracle', name: 'Miracle' },
  { id: 'Modular', name: 'Modular' },
  { id: 'Myriad', name: 'Myriad' },
  { id: 'Partner', name: 'Partner' },
  { id: 'Persist', name: 'Persist' },
  { id: 'Poisonous', name: 'Poisonous' },
  { id: 'Prize', name: 'Prize' },
  { id: 'Provoke', name: 'Provoke' },
  { id: 'Prowess', name: 'Prowess' },
  { id: 'Rampage', name: 'Rampage' },
  { id: 'Ravenous', name: 'Ravenous' },
  { id: 'Recover', name: 'Recover' },
  { id: 'Renown', name: 'Renown' },
  { id: 'Replicate', name: 'Replicate' },
  { id: 'Ripple', name: 'Ripple' },
  { id: 'Soulbond', name: 'Soulbond' },
  { id: 'Soulshift', name: 'Soulshift' },
  { id: 'Squad', name: 'Squad' },
  { id: 'Storm', name: 'Storm' },
  { id: 'Suspend', name: 'Suspend' },
  { id: 'Training', name: 'Training' },
  { id: 'Undying', name: 'Undying' },
  { id: 'Vanishing', name: 'Vanishing' },
  { id: 'Ward', name: 'Ward' },
];
