export const MISC = [
  { id: 'Abyss', name: 'Abyss' },
  { id: 'Alternate-win_or_-loss_card', name: 'Alternate-win or -loss card' },
  { id: 'Animate', name: 'Animate' },
  { id: 'Anti-discard', name: 'Anti-discard' },
  { id: 'Anti-flying', name: 'Anti-flying' },
  { id: 'Artifact_destruction', name: 'Artifact destruction' },
  { id: 'Assistance', name: 'Assistance' },
  { id: 'Attack_alone', name: 'Attack alone' },
  { id: 'Balance', name: 'Balance' },
  { id: 'Basic_land_counting', name: 'Basic land counting' },
  { id: 'Batching', name: 'Batching' },
  { id: 'Bidding', name: 'Bidding' },
  { id: 'Biting', name: 'Biting' },
  { id: 'Bloodthirsty_vampire', name: 'Bloodthirsty vampire' },
  { id: 'Board_wipe', name: 'Board wipe' },
  { id: 'Bounce', name: 'Bounce' },
  { id: 'Cantrip', name: 'Cantrip' },
  { id: 'Card_filtering', name: 'Card filtering' },
  { id: 'Charm', name: 'Charm' },
  { id: 'City%27s_Blessing', name: 'City\'s Blessing' },
  { id: 'Clockwork_creature', name: 'Clockwork creature' },
  { id: 'Color_changer', name: 'Color changer' },
  { id: 'Commander_storm', name: 'Commander storm' },
  { id: 'Creature_pumping', name: 'Creature pumping' },
  { id: 'Cremate', name: 'Cremate' },
  { id: 'Curiosity', name: 'Curiosity' },
  { id: 'Daunt', name: 'Daunt' },
  { id: 'Day_and_night', name: 'Day and night' },
  { id: 'Dehydration', name: 'Dehydration' },
  { id: 'Devil%27s_Deal', name: 'Devil\'s Deal' },
  { id: 'Devotion', name: 'Devotion' },
  { id: 'Dexterity_card', name: 'Dexterity card' },
  { id: 'Dice_rolling', name: 'Dice rolling' },
  { id: 'Dies', name: 'Dies' },
  { id: 'Direct_damage', name: 'Direct damage' },
  { id: 'Divvy', name: 'Divvy' },
  { id: 'Drain_life', name: 'Drain life' },
  { id: 'Draw', name: 'Draw' },
  { id: 'En-Kor_ability', name: 'En-Kor ability' },
  { id: 'Enchantress', name: 'Enchantress' },
  { id: 'Ending_turns_and_phases', name: 'Ending turns and phases' },
  { id: 'Energy', name: 'Energy' },
  { id: 'Enters_the_battlefield', name: 'Enters the battlefield' },
  { id: 'Firebreathing', name: 'Firebreathing' },
  { id: 'Flicker', name: 'Flicker' },
  { id: 'Flipping_a_coin', name: 'Flipping a coin' },
  { id: 'Fog', name: 'Fog' },
  { id: 'Free_mechanic', name: 'Free mechanic' },
  { id: 'Free_spell', name: 'Free spell' },
  { id: 'Freeze', name: 'Freeze' },
  { id: 'Gaseous_form', name: 'Gaseous form' },
  { id: 'Gating', name: 'Gating' },
  { id: 'Generic_mana_cost', name: 'Generic mana cost' },
  { id: 'Ghostly_Prison_effect', name: 'Ghostly Prison effect' },
  { id: 'Growing_enchantment', name: 'Growing enchantment' },
  { id: 'Guildmage', name: 'Guildmage' },
  { id: 'High_flying', name: 'High flying' },
  { id: 'Historic', name: 'Historic' },
  { id: 'Hoser', name: 'Hoser' },
  { id: 'Hybrid_mana', name: 'Hybrid mana' },
  { id: 'Illusion_ability', name: 'Illusion ability' },
  { id: 'Imprisoning', name: 'Imprisoning' },
  { id: 'Impulse', name: 'Impulse' },
  { id: 'Initiative', name: 'Initiative' },
  { id: 'Intrinsic_ability', name: 'Intrinsic ability' },
  { id: 'Invoker', name: 'Invoker' },
  { id: 'Jump', name: 'Jump' },
  { id: 'Kindle', name: 'Kindle' },
  { id: 'Lace', name: 'Lace' },
  { id: 'Land_changer', name: 'Land changer' },
  { id: 'Land_destruction', name: 'Land destruction' },
  { id: 'Lobotomy', name: 'Lobotomy' },
  { id: 'Loners', name: 'Loners' },
  { id: 'Looting', name: 'Looting' },
  { id: 'Lucky_charm', name: 'Lucky charm' },
  { id: 'Lure', name: 'Lure' },
  { id: 'Mana_acceleration', name: 'Mana acceleration' },
  { id: 'Mana_stone', name: 'Mana stone' },
  { id: 'Mana_washing', name: 'Mana washing' },
  { id: 'Maro_ability', name: 'Maro ability' },
  { id: 'Meddling', name: 'Meddling' },
  { id: 'Mix-and-match', name: 'Mix-and-match' },
  { id: 'Modal', name: 'Modal' },
  { id: 'Modified', name: 'Modified' },
  { id: 'Monarch', name: 'Monarch' },
  { id: 'Nettling', name: 'Nettling' },
  { id: 'Nightmare', name: 'Nightmare' },
  { id: 'Odd_or_even', name: 'Odd or even' },
  { id: 'Orochi_ability', name: 'Orochi ability' },
  { id: 'Pacifism', name: 'Pacifism' },
  { id: 'Panic', name: 'Panic' },
  { id: 'Party', name: 'Party' },
  { id: 'Phasing', name: 'Phasing' },
  { id: 'Phyrexian_hybrid_mana', name: 'Phyrexian hybrid mana' },
  { id: 'Phyrexian_mana', name: 'Phyrexian mana' },
  { id: 'Ping', name: 'Ping' },
  { id: 'Pitch_spell', name: 'Pitch spell' },
  { id: 'Plot_booster', name: 'Plot booster' },
  { id: 'Poison_counter', name: 'Poison counter' },
  { id: 'Poisoned', name: 'Poisoned' },
  { id: 'Polymorph', name: 'Polymorph' },
  { id: 'Power/Toughness_switcher', name: 'Power/Toughness switcher' },
  { id: 'Predefined_token', name: 'Predefined token' },
  { id: 'Punisher', name: 'Punisher' },
  { id: 'Quest', name: 'Quest' },
  { id: 'Ramp', name: 'Ramp' },
  { id: 'Ransom', name: 'Ransom' },
  { id: 'Reanimation', name: 'Reanimation' },
  { id: 'Redirection_effect', name: 'Redirection effect' },
  { id: 'Relentless', name: 'Relentless' },
  { id: 'Removal', name: 'Removal' },
  { id: 'Requirement', name: 'Requirement' },
  { id: 'Reverse_threshold', name: 'Reverse threshold' },
  { id: 'Rewards_for_death', name: 'Rewards for death' },
  { id: 'Rhystic', name: 'Rhystic' },
  { id: 'Rule-setting', name: 'Rule-setting' },
  { id: 'Ruthless', name: 'Ruthless' },
  { id: 'Saboteur', name: 'Saboteur' },
  { id: 'Sengir_ability', name: 'Sengir ability' },
  { id: 'Sleeping_enchantment', name: 'Sleeping enchantment' },
  { id: 'Spellbook', name: 'Spellbook' },
  { id: 'Spellshaper', name: 'Spellshaper' },
  { id: 'Spiritcraft', name: 'Spiritcraft' },
  { id: 'Split_card', name: 'Split card' },
  { id: 'Stalking', name: 'Stalking' },
  { id: 'Stealing', name: 'Stealing' },
  { id: 'Subgame', name: 'Subgame' },
  { id: 'Taxing', name: 'Taxing' },
  { id: 'Text-changing_effect', name: 'Text-changing effect' },
  { id: 'Timespiraling', name: 'Timespiraling' },
  { id: 'Token_card', name: 'Token card' },
  { id: 'Torment_ability', name: 'Torment ability' },
  { id: 'Transformation', name: 'Transformation' },
  { id: 'Tribal_coupling', name: 'Tribal coupling' },
  { id: 'Tuck', name: 'Tuck' },
  { id: 'Tutor', name: 'Tutor' },
  { id: 'Unblockable', name: 'Unblockable' },
  { id: 'Uncounterable', name: 'Uncounterable' },
  { id: 'Unpreventable_damage', name: 'Unpreventable damage' },
  { id: 'Untrample', name: 'Untrample' },
  { id: 'Venom', name: 'Venom' },
  { id: 'Warlord', name: 'Warlord' },
  { id: 'Whammy_deck', name: 'Whammy deck' },
  { id: 'Wheel_effect', name: 'Wheel effect' },
  { id: 'Wisdom', name: 'Wisdom' },
  { id: 'Wish', name: 'Wish' },
  { id: 'Wrath_effect', name: 'Wrath effect' },
];
